#!/usr/bin/env python3
"""Generate private developer fixtures; never repair or replace existing credentials."""
import os
from pathlib import Path
import secrets
import stat
import sys


def validate_identity(uid: int, gid: int) -> None:
    if not all(type(value) is int and 0 < value < 2**32 - 1 for value in (uid, gid)):
        raise ValueError("Run bootstrap as a non-root user with a nonzero primary group.")


def private_file(path: Path, uid: int) -> None:
    info = path.lstat()
    if not stat.S_ISREG(info.st_mode) or info.st_uid != uid or stat.S_IMODE(info.st_mode) != 0o600:
        raise ValueError("Existing credentials must be owner-owned regular files with mode 0600; no files were changed. Review and repair their permissions yourself.")


def provision(root: Path) -> str:
    uid, gid = os.getuid(), os.getgid()
    validate_identity(uid, gid)
    env, directory = root / ".env", root / ".secrets"
    key = directory / "signing.key"
    if directory.is_symlink() or env.is_symlink() or key.is_symlink():
        raise ValueError("Credential paths must not be symbolic links.")
    if directory.exists():
        info = directory.stat()
        if not stat.S_ISDIR(info.st_mode) or info.st_uid != uid or stat.S_IMODE(info.st_mode) != 0o700:
            raise ValueError("Existing secret directory must be owner-owned with mode 0700; no files were changed.")
    if env.exists() or key.exists():
        if not (env.exists() and key.exists()):
            raise ValueError("Incomplete existing configuration; restore or move it yourself before regeneration.")
        private_file(env, uid)
        private_file(key, uid)
        if not 32 <= key.stat().st_size <= 4096:
            raise ValueError("Existing signing key has an invalid size; no files were changed.")
        lines = env.read_text().splitlines()
        for name, value in (("FUSE_RUNTIME_UID", uid), ("FUSE_RUNTIME_GID", gid)):
            matches = [line.partition("=")[2] for line in lines if line.startswith(name + "=")]
            if matches != [str(value)]:
                raise ValueError(f"Existing configuration needs exactly {name}={value} for private Compose secret access; update it yourself. No credentials were changed.")
        return "Existing private configuration retained."
    template = (root / ".env.example").read_text()
    lines = [line.replace("CHANGE_ME", secrets.token_hex(32)) if "CHANGE_ME" in line and not line.startswith("#") else line for line in template.splitlines()]
    if any(line.startswith(("FUSE_RUNTIME_UID=", "FUSE_RUNTIME_GID=")) for line in lines):
        raise ValueError("Runtime identity is generated by bootstrap, not configured in the template.")
    lines += ["", "# Developer Compose runs as this non-root host identity to read its 0600 secret.", f"FUSE_RUNTIME_UID={uid}", f"FUSE_RUNTIME_GID={gid}"]
    directory.mkdir(mode=0o700, exist_ok=True)
    created = []
    try:
        for path, content in ((key, secrets.token_bytes(32)), (env, ("\n".join(lines) + "\n").encode())):
            fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
            created.append(path)
            with os.fdopen(fd, "wb") as output:
                os.fchmod(output.fileno(), 0o600)
                output.write(content)
    except BaseException:
        for path in reversed(created):
            path.unlink()
        raise
    return "Local random demo credentials generated privately. Next: docker compose up --build"


if __name__ == "__main__":
    try:
        print(provision(Path(__file__).resolve().parent.parent))
    except (OSError, ValueError) as error:
        print(str(error), file=sys.stderr)
        sys.exit(1)
